services:
  _defaults:
    autowire: true
    autoconfigure: true
    public: false

  AndrasOtto\Csp\ContentObject\ScriptContentObject:
    tags:
      - name: frontend.contentobject
        identifier: 'SCRIPT'